# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Wizgrav
tagline:          'You Nexus, huh?'
description:      "I'm an interface engineer."
url:              http://wizgrav.com
baseurl:          /

author:
  name:           'Yannis Gravezas'
  url:            https://twitter.com/wizgrav

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/wizgrav
